version: '3.8'

services:
  delivery-bot:
    build: .
    container_name: delivery-bot
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./data:/app/data
      - ./database.json:/app/database.json
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
